### ISSUE TITLE
Pod API returning `{"error":"No pod found with the specified name."}` for valid pods

### ISSUE THREAD

**Issue by kylef** [CocoaPods/trunk.cocoapods.org#107]
Broken pods:

- SLTableViewContent https://trunk.cocoapods.org/api/v1/pods/SLTableViewContent
- WSDownloader https://trunk.cocoapods.org/api/v1/pods/WSDownloader

Seems to be some sync published state.

**Comment by segiddins** [comment]
Cannot reproduce.

**Comment by PoojaChirp** [comment]
Hi Cocoapods team,

I have got the similar issue. I'm trying to delete a few pods that were added. Every time I run the command -"pod trunk deprecate <pod name> " I get the following output "[!] No pod found with the specified name.". Though "pod trunk me" lists all of these pods.  Please help!
