### ISSUE TITLE
Spec validation errors are not shown when using cocoapods-trunk.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/trunk.cocoapods.org#112]
Currently we send the actual validation errors under a `data` key: https://github.com/CocoaPods/trunk.cocoapods.org/blob/a631c1d11e952ea515d4ee8d70e7663eb5f07baf/app/controllers/api/pods_controller.rb#L70

This is not what the cocoapods-trunk plugin expects: https://github.com/CocoaPods/cocoapods-trunk/blob/0.3.2/lib/pod/command/trunk.rb#L376

I think we should use the `data` form and also use that here: https://github.com/CocoaPods/trunk.cocoapods.org/blob/a631c1d11e952ea515d4ee8d70e7663eb5f07baf/app/controllers/api_controller.rb#L41

**Comment by segiddins** [comment]
CocoaPods-trunk has been updated.
