### ISSUE TITLE
Allow individual versions to be deleted.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/trunk.cocoapods.org#118]
See https://github.com/CocoaPods/Specs/issues/12833

Related to #113, but that’s about complete pods.

**Comment by segiddins** [comment]
We've done this!

**Comment by f2prateek** [comment]
@segiddins (cc @floere) re: #144 — are there docs on how users can mark a  specific version of a pod as deleted, or is some more work required elsewhere?

**Comment by segiddins** [comment]
Right now it's only via PRs to the specs repo -- were working on an API for it, though.
