### ISSUE TITLE
Duplicate Mapbox pods

### ISSUE THREAD

**Issue by orta** [CocoaPods/trunk.cocoapods.org#126]
Given that `Mapbox-ios-sdk` is on their official docs: https://www.mapbox.com/mapbox-ios-sdk/#cocoapods

We should remove the dupe, and deprecate the `Mapbox` in favor of the official SDK. /cc @incanus

**Comment by incanus** [comment]
Yes! This was a chance to rename during the trunk migration. Works for me. There's a deprecation notice in the old one anyway.

**Comment by orta** [comment]
:+1:

**Comment by orta** [comment]
I've removed ( for those with trunk access, I've flagged it as deleted ) the dupe.
