### ISSUE TITLE
Add rack-attack

### ISSUE THREAD

**Issue by orta** [CocoaPods/trunk.cocoapods.org#133]
Someone using our API to find out all the latest spec versions can effectively DDOS, we should add a request limiter or something similar. ( Though take note that Amazon upload 10-15 pods simultaneously, so we want to be aware of general use cases like this. )

**Comment by alloy** [comment]
[rack-attack](https://github.com/kickstarter/rack-attack) does seem like the best current choice. Being on Heroku means we definitely need a cache service that outlives the Herokun instances. I think the [free memcached plans are fine for our needs](https://addons.heroku.com/memcachedcloud?utm_campaign=search&utm_medium=dashboard&utm_source=addons).

With regards to keeping use-cases like e.g. Amazon’s in mind, the main thing that needs to be throttled right now is massive amounts of GET requests, not so much POST requests.

**Comment by orta** [comment]
:+1:

**Comment by kylef** [comment]
> Being on Heroku means we definitely need a cache service that outlives the Herokun instances.

@alloy the CDN can do this for entire resources, I can enable it. Just need to provide cache-control headers to the requests so it knows how to cache each resource.

**Comment by floere** [comment]
@kylef This is resolved, isn't it?

**Comment by segiddins** [comment]
nope, trunk doesn't yet seem to be cached via cloudflare

**Comment by orta** [comment]
#160 brough this in.
