### ISSUE TITLE
pod trunk register - Internal Server Error

### ISSUE THREAD

**Issue by dmdeller** [CocoaPods/trunk.cocoapods.org#134]
Ran the command:

    pod trunk register [redacted] 'David Deller' --description='[redacted]'

Got a link in my inbox that looked like:

    https://trunk.cocoapods.org/sessions/verify/[redacted]

Clicking the link let do a page with words 'Internal Server Error' and no other content. Refreshing the page had the same result.

Let me know if you need non-redacted versions.

**Comment by segiddins** [comment]
Trunk itself appears to be down right now...

**Comment by segiddins** [comment]
This has been resolved.
