### ISSUE TITLE
Run a lint on whether the code is accessible

### ISSUE THREAD

**Issue by orta** [CocoaPods/trunk.cocoapods.org#136]
for git: `git ls-remote git://github.com/drewmccormack/dropbox-sdk-ios.git HEAD`

![screen shot 2015-06-04 at 12 52 11 pm](https://cloud.githubusercontent.com/assets/49038/7989606/b3462f00-0ab8-11e5-8d8a-e4bc79e9ea4f.png)

for http `curl` or nap.

For others it's probably fine to just skip, we're hitting 90%+ with those two cases

**Comment by orta** [comment]
this got merged

**Comment by brianpartridge** [comment]
Awesome. Thank you @orta !
