### ISSUE TITLE
Claim a trunk page is crashing

### ISSUE THREAD

**Issue by orta** [CocoaPods/trunk.cocoapods.org#138]
This explains a few disputes.

**Comment by segiddins** [comment]
I can't repro this -- @orta do you have logs for this crash handy?

**Comment by orta** [comment]
afraid not, I can't re-pro either.

**Comment by orta** [comment]
https://github.com/CocoaPods/Specs/pull/13343#issuecomment-124577768

**Comment by orta** [comment]
#153 should fix this

**Comment by orta** [comment]
I think it did, we're seeing a lot less disputes in trunk.
