### ISSUE TITLE
Command to remove the cocoapod spec completely

### ISSUE THREAD

**Issue by mposSVK** [CocoaPods/trunk.cocoapods.org#139]
Hello,

We would like to be able to remove the cocoapod spec completely - e.g. distribution of demo library specs in the case the project ceases to exist and supporting infrastructure is no longer in operation.

Thanks.

Rado

**Comment by orta** [comment]
We're extremely cautious about removing pods completely, the database was created to be read only, so our policy is to have people submit PRs to the specs repo adding a deprecated flag: https://github.com/CocoaPods/Specs/pull/12199
