### ISSUE TITLE
podspec to delete from the Trunk database please.

### ISSUE THREAD

**Issue by King-Wizard** [CocoaPods/trunk.cocoapods.org#145]
Further to the [short conversation that I have just had with @Keith Smiley](https://github.com/CocoaPods/Specs/pull/13389#event-381658167), I allow myself to contact you in order to ask you to please delete from the trunk database the list of podspec below:

 Specs/GTNotification/1.0/GTNotification.podspec.json
Specs/GTNotification/1.1/GTNotification.podspec.json
Specs/GTNotification/1.2/GTNotification.podspec.json
Specs/GTNotification/1.3/GTNotification.podspec.json

Note: for more information, please find the link of the [commit](https://github.com/King-Wizard/Specs/commit/7a0d03e139c15067421ade8051bf5464ed6f28de) where I deleted the four podspec files. Please keep me updated on the situation, because this is the first time that I do this type of request.

**Comment by orta** [comment]
I'm afraid we're still making the deprecation [method for trunk](https://github.com/CocoaPods/trunk.cocoapods.org/pull/144) specs, so I'll leave this open and connected. The Specs repo can deal with deletions, trunk however cannot easily just have data wiped.

**Comment by King-Wizard** [comment]
Sorry but I am a little bit confused, could you please just quickly tell me what is the purpose of the Specs repo and the Trunk database?

Also what happens if only the podspec is deleted from the specs repository?

And thus what would be the perk of having data deleted from the Trunk?

Thank you in advance for your answers, I am new to all of that.

**Comment by orta** [comment]
We now support deprecating or deleting a Pod from the command line in the 1.0 beta, if you run `pod trunk delete` and `pod trunk deprecate` with `--help` it should help you do what you want independently.
