### ISSUE TITLE
Duplicate account?

### ISSUE THREAD

**Issue by clayallsopp** [CocoaPods/trunk.cocoapods.org#146]
Somehow I have two accounts: https://cocoapods.org/owners/485 https://cocoapods.org/owners/3253, which is preventing me from updating https://github.com/clayallsopp/routable-ios

i.e. I `pod trunk register clay.allsopp@gmail.com`, which works, but when I `pod trunk push` inside the Routable repo, it yells:

```
$ pod trunk push

[!] Found podspec `Routable.podspec`
Validating podspec
 -> Routable (0.2.0)

[!] Authentication token is invalid or unverified. Either verify it with the email that was sent or register a new session.
```

(apologies if there's a better place to file this issue - the "Claim Pod" form didn't allow for like fuzzy input)

**Comment by segiddins** [comment]
@clayallsopp the two accounts are registered to different emails

**Comment by clayallsopp** [comment]
What are the emails? If one is clay@usepropeller.com, I no longer have access to that

**Comment by segiddins** [comment]
Yeah, that is the other.

**Comment by clayallsopp** [comment]
Cool, so what is the next action here? I think the ideal state is that those pods are moved to the clay.allsopp@gmail.com account

**Comment by segiddins** [comment]
You should file a claim via the trunk website on those pods.

**Comment by clayallsopp** [comment]
Cool, done

**Comment by orta** [comment]
I've added your gmail to them all :+1:

**Comment by clayallsopp** [comment]
@orta lovely, thank you!
