### ISSUE TITLE
"Source code for your Pod was not accessible to CocoaPods Trunk"

### ISSUE THREAD

**Issue by billinghamj** [CocoaPods/trunk.cocoapods.org#147]
I'm trying to push my Pod "JBImageView": https://github.com/billinghamj/JBCameraView

As you can see, it is public. However I'm getting the error:

```
[!] Source code for your Pod was not accessible to CocoaPods Trunk. Is it a private repo or behind a username/password on http?
```

The spec (https://github.com/billinghamj/JBCameraView/blob/v0.1.0/JBCameraView.podspec) references https://github.com/billinghamj/JBCameraView.git tag `v0.1.0`.

Running this:

```bash
git ls-remote https://github.com/billinghamj/JBCameraView.gt v0.1.0
```

Results in:

```
5c2a6474b88211e5c5da613bff66cbb665b7926f	refs/tags/v0.1.0
```

Which is correct.

I can only assume that the process must be timing out. In the event of a timeout exception, Trunk assumes the repo is not accessible: https://github.com/CocoaPods/trunk.cocoapods.org/blob/e0be3b379138d154f8d3f4f7a2e7d9dd799970f4/app/models/specification_wrapper.rb#L67

Perhaps this should be changed to return true rather than false?

**Comment by billinghamj** [comment]
I have tried pushing about 5 times, the error consistently occurs.

**Comment by orta** [comment]
GitHub is currently being DDOS'd, so that's likely the cause, trunk has been doing this fine for a few months now.

**Comment by billinghamj** [comment]
Okay, so perhaps the behavior should be changed to return true in the event of a timeout?

**Comment by orta** [comment]
Given that the Specs repo is also on GitHub, you would still receive an error, it would just be at the stage where we make the commit instead I'm afraid.

**Comment by billinghamj** [comment]
Okay. I'll wait out the DDOS then. Thanks

**Comment by orta** [comment]
I've just successfully pushed a Pod, so if you're still having problems we should re-open.

```
Updating spec repo `master`
  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/97eb52b052a78296aefe828f2e41c34a01fd99ea/Specs/ARAnalytics/3.7.1/ARAnalytics.podspec.json
  - Log messages:
    - August 25th, 08:19: Push for `ARAnalytics 3.7.1' initiated.
    - August 25th, 08:19: Push for `ARAnalytics 3.7.1' has been pushed (2.841935864 s).
```

**Comment by billinghamj** [comment]
It just worked for me too. Just intermittent due to the DDOS I guess. Oh well. Thanks for the help.
