### ISSUE TITLE
Trunk has published an outdated version of the repository

### ISSUE THREAD

**Issue by groue** [CocoaPods/trunk.cocoapods.org#154]
Hello,

https://cocoapods.org/pods/GRDB.swift shows the v0.28.0 version of https://github.com/groue/GRDB.swift, with the outdated v0.27.0 versions of README.md and the CHANGELOG.md.

Compare the README of https://cocoapods.org/pods/GRDB.swift
With the version at v0.28.0: https://github.com/groue/GRDB.swift/blob/v0.28.0/README.md

Do you know what happened?

The `pod trunk push` has run fine, as long as I know:

```
$ pod trunk push

[!] Found podspec `GRDB.swift.podspec`
Updating spec repo `master`
Validating podspec
 -> GRDB.swift (0.28.0)

Updating spec repo `master`
  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/aa6a96127d6fead6d9d01106c759355b8f758265/Specs/GRDB.swift/0.28.0/GRDB.swift.podspec.json
  - Log messages:
    - November 13th, 08:03: Push for `GRDB.swift 0.28.0' initiated.
    - November 13th, 08:03: Push for `GRDB.swift 0.28.0' has been pushed (0.99717332 s).
```

**Comment by groue** [comment]
Also, the documentation for v0.28.0 http://cocoadocs.org/docsets/GRDB.swift/0.28.0/index.html returns a 404, when the v.0.27.0 works fine: http://cocoadocs.org/docsets/GRDB.swift/0.27.0/index.html. Maybe this issue does not belong to this repository, I apologize.

**Comment by orta** [comment]
Looking at https://status.cocoapods.org it seems that _something_ is up with CocoaDocs, but what that is I don't really know without investigation:

<img width="876" alt="screen shot 2015-11-13 at 06 26 09" src="https://cloud.githubusercontent.com/assets/49038/11145018/7a0595dc-89cf-11e5-8bb0-2860b8918c03.png">

**Comment by groue** [comment]
It continues: I've just pushed v0.29.0, and https://cocoapods.org/pods/GRDB.swift keeps on displaying outdated v0.27.0 README and CHANGELOG.

**Comment by orta** [comment]
Looks like this is is due to the preview thumbnails:

The Mac is currently running headless because I've not logged in via screen sharing since the last reboot, but the Headline image generator requires a screen. This locks the process. Gonna need to re-run a weeks worth of docs probably.

```
 vendor/Headliner.app/Contents/MacOS/Headliner GRDB.swift "Versatile SQLite toolkit for Swift." "pod @@GRDB.swift@@, @@~> 0.29@@" "Great Tests" "Great Docs" "MIT" "Swift" /Users/cocoadocs/cocoadocs.org/activity/docsets/GRDB.swift/0.29.0/preview.png
Nov 14 08:09:37  Headliner[1850] <Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
Nov 14 08:09:37  Headliner[1850] <Error>: This user is not allowed access to the window system right now.
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
Nov 14 08:09:37  Headliner[1850] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
```

**Comment by groue** [comment]
Happy I could help spotting this minor trouble!

**Comment by orta** [comment]
Thanks a lot, now to figure out how to convert the app to run headless

**Comment by orta** [comment]
Alright! This is fixed, https://github.com/CocoaPods/cocoadocs.org/commit/c3456e00051fe387217f9abbc9d10c6dfe2840a6 - the app makes no assumptions that you can create a window.

**Comment by orta** [comment]
And I re-ran GRDB and everything seems to look good from my side

**Comment by groue** [comment]
Wow, such a big change :-) Thanks, @orta!

**Comment by groue** [comment]
It looks like I can close this issue, now.
