### ISSUE TITLE
PodTest122

### ISSUE THREAD

**Issue by earulraj** [CocoaPods/trunk.cocoapods.org#159]
Hi this pod was created by me for test purposes can you please remove it.

**Comment by segiddins** [comment]
You'll need to make a PR to the specs repo, but we highly discourage deleting pods

**Comment by orta** [comment]
We now support deprecating or deleting a Pod from the command line in the 1.0 beta, if you run `pod trunk delete` and `pod trunk deprecate` with `--help` it should help you do what you want independently.
