### ISSUE TITLE
Remove pod 'UPEmbeddedTextViewM2' from trunk 

### ISSUE THREAD

**Issue by AdrianaPineda** [CocoaPods/trunk.cocoapods.org#161]
I want to remove the pod 'UPEmbeddedTextViewM2'. I'm the owner and I no longer need it since I created another one with a more meaningful name (see 'UPEmbeddedTextViewManager')
I already made a PR  in the specs repo (https://github.com/CocoaPods/Specs/pull/13730)

Thanks!
Adriana Pineda

**Comment by orta** [comment]
Closing as this is covered by 1.0's command line API
