### ISSUE TITLE
Remove my CustomLabel specification

### ISSUE THREAD

**Issue by yogeshbh** [CocoaPods/trunk.cocoapods.org#174]
I was learning cocoa pods and so tried some commands. I have deleted the original project. Please remove this specification from trunk database. Sincere apologies. 

https://raw.githubusercontent.com/CocoaPods/Specs/58b74e2394e337849aefd4919e129bb13bd6339a/Specs/CustomLabel/0.1.0/CustomLabel.podspec.json

**Comment by orta** [comment]
Please use the `pod trunk delete` command in the CocoaPods 1.0 betas, we aim to not curate the Specs repo.
