### ISSUE TITLE
Rename GooglePlaces to GooglePlacesAPI as required by Google.

### ISSUE THREAD

**Issue by honghaoz** [CocoaPods/trunk.cocoapods.org#182]
Hi, 

As required by Google. I'd like to rename my pod GooglePlaces to GooglePlacesAPI.

I thought about [deprecating](https://guides.cocoapods.org/syntax/podspec.html#deprecated) this Pod. However, I believe the old pod name still conflicts with Google's coming one.

So I think make an amending PR to rename the name is the right way.

Any other better solution? Thanks

This is the PR I posted https://github.com/CocoaPods/Specs/pull/14039

**Comment by segiddins** [comment]
You can't change the name of a pod. The best way would be to deprecate and have the old pod just depend on the new one.

**Comment by honghaoz** [comment]
@segiddins If I deprecate the old one, is the old name still occupied? So that Google can used that pod name. Otherwise, I have to delete it I guess?

**Comment by segiddins** [comment]
Yeah, or you can give ownership of the pod to google
