### ISSUE TITLE
Remove PredictIO

### ISSUE THREAD

**Issue by haseebOptini** [CocoaPods/trunk.cocoapods.org#183]
i published the pod named PredictIO but because of sum issues i want to un publish my pod and delete from CocoaPods Database.

**Comment by segiddins** [comment]
`pod trunk delete` will do what you want: https://guides.cocoapods.org/terminal/commands.html#pod_trunk_delete

**Comment by haseebOptini** [comment]
i am writing a command and unable to delete the current Pod every time i run this command i get the result "[!] You are not allowed to delete this pod."
