### ISSUE TITLE
Remove 'builtiOSSDKFramework' and 'builtIO' trunk

### ISSUE THREAD

**Issue by priyankamistry09** [CocoaPods/trunk.cocoapods.org#190]
Hi,

We have 'builtiOSSDKFramework' and 'builtIO' which we already removed from Spec. We wish to remove the same from trunk as we are planning to push under the name 'BuiltIO'. Currently its throwing 'name already taken' error.

Note: 'builtIO' and 'builtiOSSDKFramework' are registered under our email i.e mobile@raweng.com

**Comment by orta** [comment]
I'm afraid we don't support changing the case of your Pods as we use a local filesystem for storage and we want to be agnostic of case insensitivity, but you can use the [trunk commands](https://guides.cocoapods.org/terminal/commands.html#group_trunk) to delete and deprecate as you want.
