### ISSUE TITLE
Undefined method `deleted' for class `Pod::TrunkApp::PodVersion' (NameError)

### ISSUE THREAD

**Issue by pxson001** [CocoaPods/trunk.cocoapods.org#201]
Hi all,

I have a problem when deploying this app on Heroku.
When I check heroku logs. I got a message like this:

 /app/app/models/pod_version.rb:36:in `alias_method': undefined method `deleted' for class `Pod::TrunkApp::PodVersion' (NameError)

Please help me to fix the problem. I really appreciate. 
I'm really happy if you guys can show me how to deploy the app step by step. 

Thank you, guys.

**Comment by orta** [comment]
You need to use the database migrations from [Humus](https://github.com/CocoaPods/humus) - this just happened to me, would love a PR mentioning that  - we have #156  to represent the issue
