### ISSUE TITLE
`404: Not Found` for Shield Badge showing Invalid Pod

### ISSUE THREAD

**Issue by codytwinton** [CocoaPods/trunk.cocoapods.org#203]
For some reason my Cocoapods badge and access is failing to show version and platform.

[![CocoaPods Version][cocoapod-v-image]][cocoapod-url]

My pod shows up properly: https://cocoapods.org/pods/SwiftyVIPER

However, my pod account shows no pods: https://cocoapods.org/owners/8966

---

These work:

https://trunk.cocoapods.org/api/v1/pods/Alamofire

https://trunk.cocoapods.org/api/v1/pods/SwiftyVIPER

---

This works: https://trunk.cocoapods.org/api/v1/pods/Alamofire/specs/latest

This returns `404: Not Found`: https://trunk.cocoapods.org/api/v1/pods/SwiftyVIPER/specs/latest

[cocoapod-url]: http://cocoapods.org/pods/SwiftyVIPER
[cocoapod-v-image]: https://img.shields.io/cocoapods/v/SwiftyVIPER.svg
[cocoapod-p-image]: https://img.shields.io/cocoapods/p/SwiftyVIPER.svg

**Comment by codytwinton** [comment]
I believe this issue may be located in this file:

`/app/controllers/api/pods_controller.rb` on `line: 70`.

**Comment by orta** [comment]
Alright- this is deployed - thanks @codytwinton
