### ISSUE TITLE
Delete version causing internal server error

### ISSUE THREAD

**Issue by frankus** [CocoaPods/trunk.cocoapods.org#211]
### Steps to Reproduce

1. Run `pod trunk delete apptentive-ios 3.3.2` (from an authorized account)

```
WARNING: It is generally considered bad behavior to remove versions of a Pod that others are depending on!
Please consider using the `deprecate` command instead.
Are you sure you want to delete this Pod version?
```

2. Enter `y` at the prompt

### Expected:

Deletes the version. 

### Actual:

Prints:
```
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.
```

**Comment by segiddins** [comment]
Internal ref https://trunk.cocoapods.org/manage/log_messages?reference=PushJob%20with%20temporary%20ID:%2070177141040920

**Comment by huangminlinux** [comment]
I get the same issue , I click to this ref ,It need input a account ,is cocoapod account ? I think I forgot the password, how to reset the password or get the password?

**Comment by Tang8330** [comment]
+1 i am unable to delete as well.

**Comment by segiddins** [comment]
It's trying to delete the preshard path from GitHub, but I don't have the time to fix this at the moment

**Comment by orta** [comment]
This is now fixed and confirmed
