### ISSUE TITLE
Unable to delete podspec with 'pod trunk delete'

### ISSUE THREAD

**Issue by DmitryFrishbuter** [CocoaPods/trunk.cocoapods.org#219]
'pod trunk me' returns this: 
```
Pods:
    - RSBTableViewManager
```
But when I try to delete podspec using 'pod trunk delete RSBTableViewManager 0.0.4', terminal returns an error: "No pod found with the specified name."

**Comment by orta** [comment]
Probably just a bad error message, looks like it was deleted: 

![screen shot 2017-01-31 at 8 44 29 am](https://cloud.githubusercontent.com/assets/49038/22467158/7f447600-e791-11e6-865b-eba53e9becf8.png)

**Comment by DmitryFrishbuter** [comment]
Yes, this pod is not exists anymore. But 'pod trunk me' tells, that the pod exists.

**Comment by orta** [comment]
I don't think we should hide that ( considering you are the only person allowed to push a new pod version with that name now ) but I would definitely accept a PR to this + cocoapods-trunk that makes it say "(deleted)" after.

**Comment by DmitryFrishbuter** [comment]
![screen shot 2017-02-01 at 09 15 36](https://cloud.githubusercontent.com/assets/10647202/22494139/251e6054-e85f-11e6-8617-764182954f11.png)

**Comment by orta** [comment]
You already own it though...

**Comment by DmitryFrishbuter** [comment]
So what should I do to delete this?

**Comment by DmitryFrishbuter** [comment]
> cocoapods-trunk that makes it say "(deleted)" after
How to make it say deleted?

**Comment by orta** [comment]
It is deleted, I confirmed that in the first reply.

> How to make it say deleted?

Fork https://github.com/cocoapods/cocoapods-trunk and check out the code for the `me` command.

**Comment by DmitryFrishbuter** [comment]
Ok, thanks:)

**Comment by DmitryFrishbuter** [comment]
I'm not familiar with ruby development. Can you please tell me what should I fix in code,  and how to use this code after fixing?

**Comment by DmitryFrishbuter** [comment]
Could you help me please?

**Comment by DmitryFrishbuter** [comment]
Thanks
