### ISSUE TITLE
Was created 6 copies of same pod

### ISSUE THREAD

**Issue by honcharenko13** [CocoaPods/trunk.cocoapods.org#222]
Was created 6 copies of same pod. Name of pod is CircleAnimatedMenu. Every time I changed version and typed "pod trunk push CircleAnimatedMenu.podspec". First 5 times it was with warnings. Last - without. I don't know is it because of my mistakes or not ? How can I remove redundant copies and leave only one?

**Comment by orta** [comment]
This is likely just a bug on the search, occasionally it pops up and then disappears within a day, we don't allow duplicates in the database - this should be fine

**Comment by honcharenko13** [comment]
Thanks for quick answer.
