### ISSUE TITLE
Pod with source repo deleted: shall we deprecate the pod?

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/trunk.cocoapods.org#232]
I found https://cocoapods.org/pods/SKUMShareView no longer exists on Github. So installing the pod is not possible anymore.

I'm not the owner of this pod, but can I submit a pull request to make it deprecated? Or are there better solutions?

**Comment by dnkoutso** [comment]
If you click on the "See podspec" it takes me to this page https://github.com/CocoaPods/Specs/blob/master/Specs/a/0/f/SKUMShareView/1.0.3/SKUMShareView.podspec.json

**Comment by dnkoutso** [comment]
OH, nevermind the actual github repo for its source is no longer present. To my knowledge we do not manually manage this and let owners instead.

**Comment by Coeur** [comment]
But owner probably doesn't care...
So there is no action we can take to hide this broken pod?

**Comment by orta** [comment]
Afraid not, we (as the core team) don't police the Specs repo unless it's actively hurting the community, it's up to the owners to decide to have it pulled. Send them an email?

**Comment by Coeur** [comment]
@orta

This will automatically return a **404 Not Found**:

    $ curl -i "https://api.github.com/repos/ZhaoBingDong/SKUMShareView"

So we could automate hiding some specs which are based on dead sources.

**Comment by orta** [comment]
Yeah, in theory metrics.cocoapods.org could add that kind of information, and search could use it to reduce it's ranking, the worrying bit is false positives  and supporting every host.
