### ISSUE TITLE
API request to specs/latest redirecting to wrong URL

### ISSUE THREAD

**Issue by gbanfalvikl** [CocoaPods/trunk.cocoapods.org#234]
We released a library `KlarnaCheckoutSDK` that we took down and put up again. 

Now, requests to 
`https://trunk.cocoapods.org/api/v1/pods/KlarnaCheckoutSDK/specs/latest` redirect to what is probably the previous version of the spec, and return a 404 with `curl -siL`. 

Could you please update the spec URL? Thanks in advance!

**Comment by orta** [comment]
Looks like a dupe of https://github.com/CocoaPods/trunk.cocoapods.org/issues/233
