### ISSUE TITLE
Trying to claim a pod. But Pod is not found

### ISSUE THREAD

**Issue by philmartin83** [CocoaPods/trunk.cocoapods.org#252]
Hi, 
I'm trying to claim a pod, but I get "Unknown pod" but when I try and trunk push I get the error of **"You (<me>) are not allowed to push new versions for this pod. The owners of this pod are <someone-else>."**

But when I try and do **pod trunk info ConsentSDK.podspec** I get this "No pod found" with the specified name"

But when I search for the pod on the https://cocoapods.org it appears but the link gives me a 404.

I'm totally confused now. Any help would be good
Thanks

**Comment by orta** [comment]
`pod trunk info` works with the name of the Pod, not the Podspec - it looks like someone deleted all of the copies of ConsentSDK so it won't show up in other places

**Comment by philmartin83** [comment]
➜  tamoco-consent-sdk git:(master) ✗ pod trunk info ConsentSDK
Ignoring ffi-1.9.25 because its extensions are not built.  Try: gem pristine ffi --version 1.9.25
Ignoring redcarpet-3.4.0 because its extensions are not built.  Try: gem pristine redcarpet --version 3.4.0
Ignoring unf_ext-0.0.7.5 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.5
[!] No pod found with the specified name.

So how can I get this back then? Change the name in the PodSpec?

**Comment by orta** [comment]
Did you own the original? If not then yeah, you'll have to use a different name I'm afraid

**Comment by philmartin83** [comment]
The company owns the original but the original creator is no longer around and there is no shared ownership of the pod so I would assume in that scenario we would still need to change the name.

**Comment by philmartin83** [comment]
And does changing the name of the podspec mean I have to change the name of my Framework or just the pod spec name

**Comment by dnkoutso** [comment]
Can change spec name without changing framework name.
