### ISSUE TITLE
pod repo push fails with unknown error 

### ISSUE THREAD

**Issue by sroik** [CocoaPods/trunk.cocoapods.org#255]
Validating spec:
...
- ERROR | [iOS] unknown: Encountered an unknown error (434: unexpected token at '{
        "availability" : "(available)",
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 8",

**Comment by paulz** [comment]
experiencing the same error:
```
    - ERROR | [iOS] unknown: Encountered an unknown error (434: unexpected token at '{
') during validation.
```

while running: `bundle exec pod lib lint`
https://travis-ci.org/paulz/PerspectiveTransform/jobs/517979013#L859
but retrying it with `bundle exec pod lib lint --verbose --no-clean` succeeds

**Comment by k-kruusi** [comment]
run pod update on your example project

**Comment by gcharita** [comment]
@k-kruusi your suggestion doesn't fix the issue. I temporarily used version 1.7.4 and worked correctly.
