### ISSUE TITLE
All command `pod trunk` returns `No pod found with the specified name`

### ISSUE THREAD

**Issue by hzb** [CocoaPods/trunk.cocoapods.org#271]
#### Reproduce

- Run command `pod trunk me`, and get the result, everything is fine

    ```
    - Name:     myname
    - Email:    myemail
    - Since:    March 25th, 02:23
    - Pods:
      - podname
    - Sessions:
      - November 18th, 00:23  - March 25th, 2020 00:24. IP: XXX
      - November 18th, 22:33  - March 25th, 2020 22:58. IP: XXX
    ```
- Run command `pod trunk add-owner podname other-email-address`
 
    tried to add a new owner, but I got error `No pod found with the specified name.`

#### More

All commands  start with `pod trunk` return error `No pod found with the specified name.`

**Comment by dnkoutso** [comment]
Whats the pod name and the actual command you are running?

**Comment by hzb** [comment]
@dnkoutso 

Pod name is `notifylabel`, and the command I run is `pod trunk add-owner notifylabel hb@domain.com`, this email address is already registered on cocoapods.

**Comment by dnkoutso** [comment]
I dont see an issue here, its already registered your email. Has the pod been deleted before?

**Comment by hzb** [comment]
@dnkoutso 

I was running command `pod trunk delete notifylabel 0.0.1`, but also get the same error  with information `No pod found with the specified name`.

**Comment by dnkoutso** [comment]
the pod is currently deleted. You may want to republish for subsequent commands to work.

**Comment by hzb** [comment]
@dnkoutso 

I am a bit confused, if it has been deleted, why is it displayed when I run the command `pod trunk me`? And also I can search it on cocoapods.org.

**Comment by dnkoutso** [comment]
the search is a known issue with indexer. The `pod trunk me` maybe it works as intended as this pod belongs to you since it was first registered with you.

**Comment by hzb** [comment]
That means command `pod trunk delete` has problem too. Because I get the same error tip `No pod found with the specified name` when I run `pod trunk delete notifylabel 0.0.1`, and it was deleted actually.

**Comment by hzb** [comment]
Fixed
