### ISSUE TITLE
No email received for 'pod trunk register'

### ISSUE THREAD

**Issue by Souro7** [CocoaPods/trunk.cocoapods.org#280]
Similar to: CocoaPods/CocoaPods#4306 

Hi,

Recently we've been trying to register a machine with pod trunk register.

```
 $ pod trunk register sachin_at_mobstac_dot_com
$ [!] Please verify the session by clicking the link in the verification email that has been sent to sachin_at_mobstac_dot_com 
```

But no verification email was received.
Doing the same thing with a different email from the same domain, worked as expected.

Could you please check on your end and remove sachin_at_mobstac_dot_com from the bounce list? I think this is because the email id was disabled from our domain and was blacklisted due to 404 response.

**Comment by Souro7** [comment]
@dnkoutso Can you please help me with getting the email removed from the bounce list? Or advise me on how to reach out to the proper channel. We are really waiting on this to push an urgent release.

Thanks.

**Comment by orta** [comment]
I've removed the bounce on that email 👍

**Comment by Souro7** [comment]
Thanks! It works now.

**Comment by C4Framework** [comment]
I'm getting the same behaviour, not receiving an email to: 
info@createwithflow.com
Could you please check if there's a bounce on this email?
