### ISSUE TITLE
Cant Register, An internal server error occurred

### ISSUE THREAD

**Issue by agungjk-okadoc** [CocoaPods/trunk.cocoapods.org#284]
Hi, guys
I try to register but always face this error.

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.9.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 79\r\n\r\n"
<- "{\"email\":\"orta@cocoapods.org\",\"name\":\"Orta Therox\",\"description\":\"macbook air\"}"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Sun, 17 May 2020 02:48:20 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

**Comment by v-sharaev** [comment]
Hi
I have some error too when register in new device

**Comment by shagedorn** [comment]
We experience the same (also with our real email address, not Orta's).

**Comment by wisselin** [comment]
We also experienced same issue. 

P.S : with our real email address

**Comment by dnkoutso** [comment]
Please try again we believe the issue was resolved. Will keep this open.

**Comment by eladnava** [comment]
Works now, thanks! 💯 😄

**Comment by dnkoutso** [comment]
Closing for now, will keep an eye out.

**Comment by PaladinCrow** [comment]
This is happening again. Here is the verbose
`<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.10.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 72\r\n\r\n"
<- "{\"email\":\"redacted\",\"name\":\"redacted\",\"description\":null}"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Thu, 18 Feb 2021 04:15:10 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

Clearly broken again...

-Paladin

**Comment by skytan4** [comment]
This error is happening again:
 
 pod trunk register 'redacted' --verbose
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.10.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 71\r\n\r\n"
<- "{\"email\":\"redacted\",\"name\":redacted,\"description\":null}"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Tue, 25 May 2021 18:10:06 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

**Comment by huahuaworld** [comment]
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later
