### ISSUE TITLE
'pod trunk register' Mail not received

### ISSUE THREAD

**Issue by CCSH** [CocoaPods/trunk.cocoapods.org#294]
Hey team, thanks for your work.

I don't receive any email from pod trunk register 624089195@qq.com 'CCSH'. Am I in a blacklist or anything?

**Comment by CCSH** [comment]
Hey team, thanks for your work.

I don't receive any email from pod trunk register 624089195@qq.com 'CCSH'. Am I in a blacklist or anything?

**Comment by dlin-me** [comment]
Hey Tem, Also the same  for my email in work engineering@narratiive.com

Please help

**Comment by CCSH** [comment]
can someone help me solve this problem

**Comment by orta** [comment]
You were, it said your server rejected the email - I've removed it

**Comment by CCSH** [comment]
It worked, thank you
