### ISSUE TITLE
No email received for 'pod trunk register'

### ISSUE THREAD

**Issue by izabekz** [CocoaPods/trunk.cocoapods.org#301]
My ex colleague left the company and he was the sole owner of some pods. Now, his account is deactivated and we can't add new owners, what can we do?

**Comment by izabekz** [comment]
@dnkoutso @orta anyone pls help

**Comment by izabekz** [comment]
@dnkoutso @orta can you guys pls check the blockList? This is crazy that I can't publish new versions of pods

**Comment by izabekz** [comment]
@orta @dnkoutso guys pls help

**Comment by orta** [comment]
Alright, that should be removed from the bounce list 👍🏻

**Comment by izabekz** [comment]
Thanks very much!
