### ISSUE TITLE
Cocoapods removal

### ISSUE THREAD

**Issue by dusan-juranovic** [CocoaPods/trunk.cocoapods.org#302]
Hi,

I have published two repos to Cocoapods trunk while testing this feature. I thought it's gonna be easy to just remove them, once I get the hang of the process involved. It appears not :)
Could you please remove references to FFiOSClientSDK and ff-ios-client-sdk. They were both on my GitHub account, but I have deleted them a while ago. Although you can see they both still reference my account github.com/Yoorque.
I appreciate your help in advance.

Regards,
Dusan

**Comment by orta** [comment]
We don't do deletions for you, you can use the trunk commands to do that
