### ISSUE TITLE
No email received for 'pod trunk register'

### ISSUE THREAD

**Issue by cazador4** [CocoaPods/trunk.cocoapods.org#309]
Hi,

Recently we've been trying to register a machine with pod trunk register.

email : juan.sanzone@mercadolibre.com

But no verification email was received.
Doing the same thing with a different email from the same domain, worked as expected.

is it possible to remove from blacklist @orta ?

Thanks!

**Comment by cazador4** [comment]
Do you know how can we recover the ownership of the pods? They (Juan, Eric and Esteban) are not belong to our organization anymore (Mercadolibre). I can get the ownership of the accounts but is not possible to get the verification link (I've already tried)

**Comment by orta** [comment]
https://trunk.cocoapods.org/claims/new letting us know what new emails and pods etc

**Comment by orta** [comment]
I added you to about 10 repos, (`pod trunk me` will show them) - I'd recommend adding to all of them a shared engineering email 👍🏻

**Comment by cazador4** [comment]
Hi, sorry for the confusion but I don't see any pod in my profile. We are planning to do what you are saying then if we can recover the ownership. My email is: daniel.dgoldberg@mercadolibre.com, can you please add me in the pods (MLCardForm, MLCardDrawer, etc.) ? 

![image](https://user-images.githubusercontent.com/867465/117071922-1ba2df80-ad06-11eb-82ce-a2e0ff9e80da.png)


Ps: Another member of my team has already sent the form, but no response :( 

Thanks in advance,
Daniel

**Comment by orta** [comment]
You registered the dispute as jonathan.scar... - not that email

**Comment by cazador4** [comment]
Great, Jonathan have already sent you an email.
Thanks for your help!

**Comment by cazador4** [comment]
Hi again @orta! Sorry for the spam but Jonathan have already sent you an email and He hasn't ownership of the repos we need it.
Can you please add him to this repos (https://cocoapods.org/pods/MLCardDrawer and https://cocoapods.org/pods/MLCardForm) ? 

He has already sent the form.

We are blocked by this right now. 

Thanks,
Daniel

**Comment by orta** [comment]
Added, maybe that email went to my spam because I never saw it

**Comment by cazador4** [comment]
![giphy](https://user-images.githubusercontent.com/867465/117840998-03294c80-b253-11eb-8ac3-856e25aa997a.gif)
