### ISSUE TITLE
Unable to create a new session, 500 internal server error.

### ISSUE THREAD

**Issue by skytan4** [CocoaPods/trunk.cocoapods.org#311]
Below is the response I've been getting all day when trying to register a new session:

pod trunk register 'redacted' --verbose
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.10.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 71\r\n\r\n"
<- "{"email":"redacted","name":null,"description":null}"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Tue, 25 May 2021 18:10:06 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{"error":"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later."}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

**Comment by rdominic** [comment]
Experiencing the same problem here.

**Comment by melty710** [comment]
+1 also running into this today

**Comment by Jantsen-T** [comment]
+1

**Comment by clarachenhub** [comment]
+1

**Comment by orta** [comment]
Looks like we hit the cap of emails sent in a month due to the changes to email when a pod gets shipped to owners. 

Will look into how that's gonna cost us

**Comment by skytan4** [comment]
@orta Thanks for looking into this. In terms of publishing podspecs, do you feel this can be resolved shortly (within the day or so) or should we expect to wait until next month (June) in order to publish?

**Comment by orta** [comment]
Call it a _should_ probably be unblocked now, I'm tailing the logs to keep track

**Comment by orta** [comment]
OK, that's a no because that's triggered another problem. I'd scope it to a couple of hours at a guess.

**Comment by orta** [comment]
Call it maybe an over-estimate, I got a successful registration email now, will monitor the thread but I think it's good

**Comment by skytan4** [comment]
It worked for me! Thanks for your quick response on this @orta !

**Comment by orta** [comment]
Always worth my time to pop back for systemic issues
