### ISSUE TITLE
Source code for latest version of Pod is not accessible to CocoaPods Trunk

### ISSUE THREAD

**Issue by neildhar** [CocoaPods/trunk.cocoapods.org#320]
I've been trying to push the latest version of the pod `hermes-engine` for the last few days. ([podspec](https://github.com/facebook/hermes/blob/a725c6e9740ac1153f34dd0b20303df592ef50bd/hermes-engine.podspec))

Unfortunately, it keeps failing with the following output:
```
neildhar@neildhar-mbp ~/hermes (main) [1]> env hermes-artifact-url='https://github.com/facebook/hermes/releases/download/v0.10.0/hermes-runtime-darwin-v0.10.0.tar.gz' pod trunk push hermes-engine.podspec
Updating spec repo `trunk`
Validating podspec
/Users/neildhar/hermes/hermes-engine.podspec:8: warning: already initialized constant Pod::HermesHelper::BUILD_TYPE
/Users/neildhar/hermes/hermes-engine.podspec:8: warning: previous definition of BUILD_TYPE was here
/Users/neildhar/hermes/hermes-engine.podspec:8: warning: already initialized constant Pod::HermesHelper::BUILD_TYPE
/Users/neildhar/hermes/hermes-engine.podspec:8: warning: previous definition of BUILD_TYPE was here
 -> hermes-engine (0.10.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Using codesigning identity override:
    - NOTE  | xcodebuild:  note: Build preparation complete
    - NOTE  | xcodebuild:  note: Planning
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -

[!] Source code for your Pod was not accessible to CocoaPods Trunk. Is it a private repo or behind a username/password on http?
```

We've used the exact same command to push older versions of the pod, and have never seen this error. Has something changed in CocoaPods trunk in the last few months?

It's possible this is a similar issue to https://github.com/CocoaPods/trunk.cocoapods.org/issues/236, although `curl -LI "https://github.com/facebook/hermes/releases/download/v0.10.0/hermes-runtime-darwin-v0.10.0.tar.gz"` completes successfully.

**Comment by orta** [comment]
I don't think so - the checks for a http request hasn't changed in 7 years, and effectively asks the ruby stdlib to verify the  url. Perhaps GitHub was having issues? We've not had other reports around the http validation. 

https://github.com/CocoaPods/trunk.cocoapods.org/commit/e157bf9f066b3e86018accc33aebc4a38f1407d1/app/models/specification_wrapper.rb#L73-L75

**Comment by neildhar** [comment]
@orta thanks for taking a look, I tried a few more times over the course of a few days and it eventually seems to have mysteriously resolved itself.
