### ISSUE TITLE
How to remove not my public repo?

### ISSUE THREAD

**Issue by NikKovIos** [CocoaPods/trunk.cocoapods.org#321]
I've noticed that one repo is outdated - https://cocoapods.org/pods/Stevia
And I want to take it namespace for https://cocoapods.org/pods/SteviaLayout
How to remove the outdated repo from cocoapods?

**Comment by NikKovIos** [comment]
@orta nothing about removing not owned repositories found there.

**Comment by orta** [comment]
https://guides.cocoapods.org/terminal/commands.html#pod_trunk_delete

**Comment by NikKovIos** [comment]
@orta 👆 ..about removing **not owned** repositories..

- `Stevia` is not my repo
- The github page for it is not found 404

**Comment by orta** [comment]
Ah sure, did you ask the current owners for it? We don't really handle that because we dont know if it went pritate and is still in use etc

**Comment by NikKovIos** [comment]
I've found that the maintainer is https://github.com/phelgo, but can't connect with him. Is there any functional to remove the repo it this case?
