### ISSUE TITLE
pod trunk register - confirm session link not working

### ISSUE THREAD

**Issue by GabiGrin** [CocoaPods/trunk.cocoapods.org#323]
hey! first, thanks for the great work on CocoaPods, highly appreciated 🙌 

I'm trying to login via the CLI, using `pod trunk register gabrielg@wix.com`, and the verify links lead to
<img width="703" alt="Screen Shot 2022-02-02 at 20 22 13" src="https://user-images.githubusercontent.com/3727015/152214413-89be17f2-f4da-4cb9-a916-1b4d47977368.png">

Tried in a few hours difference and it didn't help
Here are a few other links that lead to a 404:

https://trunk.cocoapods.org/sessions/verify/6a451660
https://trunk.cocoapods.org/sessions/verify/0200a058 
https://trunk.cocoapods.org/sessions/verify/7364c166
https://trunk.cocoapods.org/sessions/verify/c6695aff

Thanks in advance!

**Comment by orta** [comment]
You likely have an email validator checking the links and accepting the session for you, it should be fine

**Comment by GabiGrin** [comment]
@orta  thanks! that was indeed the case :)
