### ISSUE TITLE
No verification email received upon registration

### ISSUE THREAD

**Issue by heguanyu** [CocoaPods/trunk.cocoapods.org#395]
Hi team,

I'm trying to register with this email address, lms-mid-pub-cocoapod-admin@linkedin.com

This is a group alias email, but I could confirmed that it is registered in public SMTP can receive external emails.

Can you help check if the verfication email was sent to this address properly?

Thank you very much!

-G

**Comment by heguanyu** [comment]
$ pod trunk register lms-mid-pub-cocoapod-admin@linkedin.com --verbose
Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
Ignoring digest-crc-0.6.4 because its extensions are not built. Try: gem pristine digest-crc --version 0.6.4
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.11.2\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 82\r\n\r\n"
<- "{\"email\":\"lms-mid-pub-cocoapod-admin@linkedin.com\",\"name\":null,\"description\":null}"
-> "HTTP/1.1 201 Created\r\n"
-> "Date: Fri, 09 Sep 2022 20:36:01 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 191\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 191 bytes...
-> "{\"created_at\":\"2022-09-09 20:36:01 UTC\",\"valid_until\":\"2023-01-15 20:36:01 UTC\",\"verified\":false,\"created_from_ip\":\"xxx\",\"description\":null,\"token\":\"xxx\"}"
read 191 bytes
Conn keep-alive
[!] Please verify the session by clicking the link in the verification email that has been sent to lms-mid-pub-cocoapod-admin@linkedin.com

**Comment by orta** [comment]
I've removed the bounce on that email, next one should go through
