### ISSUE TITLE
No receive email for 'pod trunk register'

### ISSUE THREAD

**Issue by lengge** [CocoaPods/trunk.cocoapods.org#398]
Hi,

Recently we are going to update the pod on a new computer.

pod trunk register [xinyu.ma@payby.com](mailto:xinyu.ma@payby.com) 'xinyuma'
[!] Please verify the session by clicking the link in the verification email that has been sent to [xinyu.ma@payby.com](mailto:xinyu.ma@payby.com)

But no verification email was received.
Doing the same thing with a different email from the same computer, worked as expected.

Could you please check if there are any issues on your end with the registration of the [xinyu.ma@payby.com](mailto:xinyu.ma@payby.com) email.

@orta

**Comment by lengge** [comment]
@orta Can you please enable the mail for this id [xinyu.ma@payby.com](mailto:xinyu.ma@payby.com) ?
We are not able to push updates and bug fixes because of this.
Thanks.

**Comment by orta** [comment]
I've removed the bounce on that email, next one should go through

**Comment by lengge** [comment]
@orta Hello, my mailbox still can't receive the mail 

pod trunk register xinyu.ma@payby.com --verbose

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.11.2\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 61\r\n\r\n"
<- "{\"email\":\"xinyu.ma@payby.com\",\"name\":null,\"description\":null}"
-> "HTTP/1.1 201 Created\r\n"
-> "Date: Sun, 09 Oct 2022 04:56:18 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 192\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 192 bytes...
-> "{\"created_at\":\"2022-10-09 04:56:18 UTC\",\"valid_until\":\"2023-02-14 04:56:18 UTC\",\"verified\":false,\"created_from_ip\":\"58.34.88.234\",\"description\":null,\"token\":\"cc54ac5543028f46b8d3a482a5eeab16\"}"
read 192 bytes
Conn keep-alive
