### ISSUE TITLE
Invalidate Session Token

### ISSUE THREAD

**Issue by uc-leo** [CocoaPods/trunk.cocoapods.org#426]
After [CircleCI security alert](https://circleci.com/blog/january-4-2023-security-alert/) session tokens may have been exposed and I cannot find a way to invalidate them... 

Can anybody help, please?

Thanks!

**Comment by orta** [comment]
We don't have a feature for this in the CLI + API. One strategy would be to create a new owner, move the pods over to them and then delete the old owner - the other would be to send a PR adding that feature to this repo for the API, and cocoapods/cocoapods-trunk for the CLI which would log out all the sessions for the current user.

**Comment by uc-leo** [comment]
all right @orta! thank you so much 👍
