### ISSUE TITLE
Notes on red CI

### ISSUE THREAD

**Issue by orta** [CocoaPods/trunk.cocoapods.org#457]
I think we need to be stubbing:

```
module ValidMXRecords
  def valid_mx_records?(address)
```

To get it green, but when I try to do that, it seems to still have the same behavior https://github.com/CocoaPods/trunk.cocoapods.org/commit/7eac15fa9e67046200612489286deb4f7a882757

**Comment by amorde** [comment]
Fixed in https://github.com/CocoaPods/trunk.cocoapods.org/pull/461
