### ISSUE TITLE
[Hooks] What to do with deleted specs?

### ISSUE THREAD

**Issue by alloy** [CocoaPods/trunk.cocoapods.org#46]

**Comment by segiddins** [comment]
@CocoaPods/core we need to decide what to do about this -- I say when specs get deleted via PR, they need to also be deleted from trunk

**Comment by keith** [comment]
+1

**Comment by k0nserv** [comment]
Should specs be deleted via PRs? I thought non automated changes of the specs repo were not recommended?

**Comment by segiddins** [comment]
Yes, they are deleted via PRs, but they still remain in trunk, and thus show up in search, cocoadocs, etc

**Comment by k0nserv** [comment]
Since new version and new pods are pushed via trunk wouldn't it be better to also delete them from there? My reasoning is that it's easier to delete in trunk and make changes to spec than detecting changes in spec and updating trunk accordingly

**Comment by floere** [comment]
I noticed a lot of the discussion (not necessarily here, but elsewhere, mainly) mixes what we should do as Specs owners and how Trunk should work.
Trunk is easy. It should try to mimic the Specs repo as well as possible.

Maybe it helps if we list all the cases?
So Trunk has basically 3 entities that are relevant: pods, versions, and commits.

So, here are a few deletion cases. What should happen in each case? I'll give it a try.

There seem to be two ways we can go about this:

1. Marking pods and versions.

Case | Pod | Version(s) | Commits
------------ | -------------|-----------|-----------
All versions of a pod are deleted | The pod is marked deleted | All are marked deleted | Commit is added for each version 
A few versions of a pod are deleted | - | These are marked | A commit per marked version
One version of a pod is deleted | - | Marked | A commit is added for the version
The spec of a version is deleted | - | Marked | A commit is added for the version

2. Deleting pods and versions.

Case | Pod | Version(s) | Commits
------------ | -------------|-----------|-----------
All versions of a pod are deleted | The pod is deleted | All are deleted | Commits are removed (?). 
A few versions of a pod are deleted | - | These are deleted | Commits for the deleted versions are removed (?)
One version of a pod is deleted | - | Deleted | Commits for that version are removed (?)
The spec of a version is deleted | - | Deleted | Commits for that version are removed (?)

(1) will incur work in all dependent services. However, we keep the commits/pods/version data and all related.
(2) can be handled by the database.

In any case, the hooks need to handle these cases to keep Trunk in sync with Specs.

**Comment by orta** [comment]
The Specs repo should be an end result of what happens in trunk, not the other way around. If we are going to support deleting pods, and pod versions in any way it should be via a `pod trunk yank [pod]` or `pod trunk yank [pod] 0.2.3` so that the onus is on the owner of the library to make the changes.

**Comment by AliSoftware** [comment]
I agree that trunk should be the ref and the repo its mirror, but I don't like to give the authors a way (via `pod trunk yank`) to remove their pods: it would risk to encourage people to do it or at least make them consider it, whereas for me it shouldn't be done (or if it should, we should decide if it's really relevant as a very special case or not). I'd prefer a private web form in our admin panel to allow us to delete a pod or a version on demand (on trunk then propagated on the specs repo) than a `pod trunk yank` public command allowing everyone to access this trunk API feature.

**Comment by orta** [comment]
All of the flack gets directed at us, when it's not our call to make. [Rubygems does this](http://blog.rubygems.org/2015/04/13/permadelete-on-yank.html) and they're getting on just fine.

**Comment by neonichu** [comment]
:+1: for `pod trunk yank` — we should discourage it, but in the end it should be a spec author's call, not ours

**Comment by k0nserv** [comment]
We might even wanna include a warning and confirmation step before performing the action.

**Comment by k0nserv** [comment]
Something like this

> You are about to remove `:pod_name` this will cause the builds of users who rely on `:pod_name` to fail. We recommend that you consider the implications of removing `:pod_name` from CocoaPods thoroughly before choosing to do so. Marking `:pod_name` as deprecated is recommended over removing it.
> Are you sure you want to remove `:pod_name`? (y/N)

**Comment by orta** [comment]
Yep, agree @k0nserv

**Comment by AliSoftware** [comment]
:+1: @k0nserv

**Comment by floere** [comment]
> The Specs repo should be an end result of what happens in trunk, not the other way around.

@orta Of course. Nobody ever said anything else. And whether the onus is on the owner of the library is orthogonal to the discussion how changes get in trunk. We can put the onus on the owner whether a change comes in via Specs repo or through trunk directly.

Can you move the `trunk yank` discussion off this issue and open one that deals specifically with that topic?
This one is about what we should do when a spec gets deleted. We keep mixing separate discussions, and this will not help a good end result.

**Comment by floere** [comment]
To clarify:
Whether we add a `pod yank` or not – changes that come in via Specs were explicitly allowed for being able to deal with crazy special cases, or with cases that we can't yet cover with Trunk. This issue deals with these special cases.
In a magical future where our users are more powerful (should we go that route), we may close down changes via Specs repo entirely, and remove all hooks code that changes the Trunk DB, only leaving it to trigger webhooks.

**Comment by orta** [comment]
Getting back on topic then, I think the pattern of marking as deleted is probably the best in the long run.

**Comment by floere** [comment]
So let's go with:

Case | Pod | Version(s) | Commits
------------ | -------------|-----------|-----------
All versions of a pod are deleted | The pod is marked deleted | All are marked deleted | Commit is added for each version 
A few versions of a pod are deleted | - | These are marked | A commit per marked version
One version of a pod is deleted | - | Marked | A commit is added for the version
The spec of a version is deleted | - | Marked | A commit is added for the version

**Comment by orta** [comment]
This is in.
