### ISSUE TITLE
Internal Server Error When Trying To `pod trunk register`

### ISSUE THREAD

**Issue by jshier** [CocoaPods/trunk.cocoapods.org#463]
Following today's CVE notification I tried to register my account again. I received the email properly but got an Internal Server Error page when I opened the confirmation link.

**Comment by orta** [comment]
This seems to be working, just bailing on rendering the congrats page for some reason - maybe I'll just make it return some text

**Comment by orta** [comment]
![image](https://github.com/CocoaPods/trunk.cocoapods.org/assets/49038/2dcad81a-9056-45f6-8fe0-7358ea4e46c8)

👍🏻
