### ISSUE TITLE
No receive email for 'pod trunk register'

### ISSUE THREAD

**Issue by hongseok** [CocoaPods/trunk.cocoapods.org#465]
Hello.

I don't get an e-mail after 'pod trunk register'.

> opening connection to trunk.cocoapods.org:443...
> opened
> starting SSL for trunk.cocoapods.org:443...
> SSL established, protocol: TLSv1.3, cipher: TLS_AES_128_GCM_SHA256
> <- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.14.2\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 81\r\n\r\n"
> <- "{\"email\":\"dl_ntracker_public@navercorp.com\",\"name\":\"nTracker\",\"description\":null}"
> -> "HTTP/1.1 201 Created\r\n"
> -> "Server: Cowboy\r\n"
> -> "Date: Fri, 22 Dec 2023 06:39:36 GMT\r\n"
> -> "Report-To: {\"group\":\"heroku-nel\",\"max_age\":3600,\"endpoints\":[{\"url\":\"https://nel.heroku.com/reports?ts=1703227177&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=t%2BS9NbUZYrKgipKpsMUoMlBEI1q6DJ9xByMZLllEk80%3D\"}]}\r\n"
> -> "Reporting-Endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1703227177&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=t%2BS9NbUZYrKgipKpsMUoMlBEI1q6DJ9xByMZLllEk80%3D\r\n"
> -> "Nel: {\"report_to\":\"heroku-nel\",\"max_age\":3600,\"success_fraction\":0.005,\"failure_fraction\":0.05,\"response_headers\":[\"Via\"]}\r\n"
> -> "Connection: keep-alive\r\n"
> -> "Strict-Transport-Security: max-age=31536000\r\n"
> -> "Content-Type: application/json\r\n"
> -> "X-Content-Type-Options: nosniff\r\n"
> -> "Content-Length: 194\r\n"
> -> "Via: 1.1 vegur\r\n"
> -> "\r\n"
> reading 194 bytes...
> -> "{\"created_at\":\"2023-12-22 06:39:37 UTC\",\"valid_until\":\"2024-04-28 06:39:37 UTC\",\"verified\":false,\"created_from_ip\":\"121.157.40.232\",\"description\":null,\"token\":\"9499dc782c0be4197cc2fe271561eb86\"}"
> read 194 bytes
> Conn keep-alive
> [!] Ple

ase verify the session by clicking the link in the verification email that has been sent to dl_ntracker_public@navercorp.com

**Comment by kwojc** [comment]
:+1:  - I have the same problem. With only one e-mail in our domain :cry:

**Comment by kwojc** [comment]
@amorde Could you check it? I also wrote e-mail to info@cocoapods.com

**Comment by hongseok** [comment]
I still can't get the mail.

**Comment by kwojc** [comment]
Please help @alloy @benasher44 @endocrimes @esttorhe @fabiopelosin @floere @joe-loco @joshkalpin @k0nserv @keith @manuyavuz @mk @mrackwitz @mtitolo @neonichu @nwest @orta @paulb777 @segiddins

**Comment by orta** [comment]
Let's not be rude here @kwojc - people do open source in their spare time.

**Comment by kwojc** [comment]
@orta I know it, but there is no response since december in this thread. So? Community is dead?

**Comment by kwojc** [comment]
@orta as I notices, you probably have access to CocoaPods Servers. We will be so glad if you can jump into logs of smtp :)

**Comment by amorde** [comment]
@hongseok This is the error we got when attempting to email you:

```
550 5.1.1 No such user r20wMe+kRkCgg0CgUhoKbg - nsmtp
```

**Comment by kwojc** [comment]
@amorde how about devs+ios@tpay.com ? We get that email once or twice, and then - silence.

**Comment by hongseok** [comment]
@amorde Thanks for response.

I can successfully receive mail from other mail service (for example, gmail) to 'dl_ntracker_public@navercorp.com '.
I asked the mail server administrator of 'navercorp.com ', he said that it seems to be an issue on the sender side.
If there is an additional log, it will help to identify the cause.
- Source server IP address
- Full contents of return mail and error messages
- Full messages answered by the receiving server (ex. 4.3.2 Your ip blocked from this server xxxxxxxxxxxxxx - nsmtp)

**Comment by hongseok** [comment]
@amorde I'm sorry, but can you check this issue.

**Comment by amorde** [comment]
I can't see any recent attempts to send mail to that address @hongseok - have you tried again recently?

**Comment by amorde** [comment]
We use [sendgrid](http://sendgrid.com) for sending out emails so we only have access to the logs they provide us, and we don't have much control to address specific issues that might arise with specific email providers.

**Comment by hongseok** [comment]
@amorde I tried two times at '2024-02-20 06:45:36 UTC'. I still haven't received a verification email.

> pod trunk register dl_ntracker_public@navercorp.com 'nTracker' --verbose
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.3, cipher: AEAD-CHACHA20-POLY1305-SHA256
<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.14.3\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 81\r\n\r\n"
<- "{\"email\":\"dl_ntracker_public@navercorp.com\",\"name\":\"nTracker\",\"description\":null}"
-> "HTTP/1.1 201 Created\r\n"
-> "Server: Cowboy\r\n"
-> "Date: Tue, 20 Feb 2024 06:45:36 GMT\r\n"
-> "Report-To: {\"group\":\"heroku-nel\",\"max_age\":3600,\"endpoints\":[{\"url\":\"https://nel.heroku.com/reports?ts=1708411536&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=k5xjl%2BTWhf3gXVtEGzvwBnxCxHxSXYWI0Xb%2B484%2BUeo%3D\"}]}\r\n"
-> "Reporting-Endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1708411536&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=k5xjl%2BTWhf3gXVtEGzvwBnxCxHxSXYWI0Xb%2B484%2BUeo%3D\r\n"
-> "Nel: {\"report_to\":\"heroku-nel\",\"max_age\":3600,\"success_fraction\":0.005,\"failure_fraction\":0.05,\"response_headers\":[\"Via\"]}\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Content-Length: 194\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 194 bytes...
-> "{\"created_at\":\"2024-02-20 06:45:36 UTC\",\"valid_until\":\"2024-06-27 06:45:36 UTC\",\"verified\":false,\"created_from_ip\":\"121.157.40.232\",\"description\":null,\"token\":\"18a5c971189fa0417e958a3e677e2224\"}"
read 194 bytes
Conn keep-alive
[!] Please verify the session by clicking the link in the verification email that has been sent to dl_ntracker_public@navercorp.com

**Comment by orta** [comment]
Give it a shot now

**Comment by orta** [comment]
I've also removed the bounce on `de...ios@tpay.com`

**Comment by hongseok** [comment]
We have received your email successfully, this issue has been resolved, thank you for your help.
