### ISSUE TITLE
[API] Pods since date

### ISSUE THREAD

**Issue by orta** [CocoaPods/trunk.cocoapods.org#97]
Let's say hypothetically something I build might go down, doesn't happen in reality. Better to be sure though, someone else's servers might have down-time though. 

They would want the ability to find out what has changed since the date it went down. Sending the same data as we do with a normal push is fine. Requesting for a friend. @alloy said it makes sense.

**Comment by segiddins** [comment]
Feeds already has logic for this, but I'm very concerned if this isn't rate-limited.

**Comment by orta** [comment]
I'm closing, I've not needed this.
